### ISSUE TITLE
Payment Lines do not have an "Id"

### ISSUE THREAD

**Issue by toddgeist** [geistinteractive/qboSync#92]
Payment Lines have no "id". 

These two scripts
* Get ( children )
* Save Child qbo_id To Field ( entityJSON )

need a qbo_id.

**Comment by toddgeist** [comment]
I am experimenting with using the parent_id and the $n variable in the loop to construct one.

**Comment by dansmith65** [comment]
- [ ] Before closing this issue, the `Get ( children ) Copy` should probably be deleted.

**Comment by dansmith65** [comment]
I'm going to have to change something with this code because when creating a new Payment record, the `Get ( children )` script doesn't have access to the parent's qbo_id value. I'm still deciding how to best handle it; this comment is just to document why I had to change it.

**Comment by dansmith65** [comment]
I ended up just dropping the parent's qbo_id and only using a serial value. I don't see any reason why more than that is necessary.
