### ISSUE TITLE
Support Payments Sync.

### ISSUE THREAD

**Issue by toddgeist** [geistinteractive/qboSync#94]
I have a version of fmQBO, that I think supports Payments Data sync pretty well.  It is based on the latest public version.  I'd like this to be in the core. Payments are kind of a pain and is common so I think this kind of makes sense.

Besides the additional records, TOs, and Scripts.  there were a couple if changes I need to make to the other core scripts.  I have recorded those as Issues, #93 and #92. They are fixed in this version.

I have marked them in comments with #GH#92, and #GH#93 for searching with FMPerception.

Since this is based on the latest rev, you may be able to just adopt the file as Master. But I'd recommend testing first.

**Comment by toddgeist** [comment]
Here is the file.
[fmQBO2.fmp12.zip](https://github.com/geistinteractive/qboSync/files/674284/fmQBO2.fmp12.zip)

**Comment by toddgeist** [comment]
We can decide about the UI later. 

Maybe one easy thing we can do is to just remove the Entity records for Payment and PaymentMethod.  That will stop them from Syncing and make them pretty easy to turn on.

**Comment by dansmith65** [comment]
> Maybe one easy thing we can do is to just remove the Entity records for Payment and PaymentMethod. That will stop them from Syncing and make them pretty easy to turn on.

Can't the send and get boxes just be unchecked to disable syncing Payments? Since they are not in the UI, that could even be the default value in the released file.

**Comment by dansmith65** [comment]
May want to rename `PaymentLines` table to `PaymentLine`; I've been using singular naming for tables.

**Comment by toddgeist** [comment]
I don't think it is needed.  I was probably just copying and pasting

**Comment by toddgeist** [comment]
@dansmith65 is this getting worked on?  I need these last couple of things done so I can move forward on other tracks

**Comment by dansmith65** [comment]
Sorry for the delay; I've been distracted by other projects. Will get to it
asap.

**Comment by dansmith65** [comment]
The file you worked on has a new field `QBOConfig::InvoiceStartDate` with comment: custom for #5280#. I don't understand what that comment is referring to; I'm guessing it's one of your internal reference numbers. Do you want me to leave that field in the file? If so, please provide instructions on changes you'd like me to make to it, if any. I would suggest changing the comment and the `Invoice Map: Get` script to ignore the field if it's empty.

**Comment by toddgeist** [comment]
You can delete it

it was for a custom project

**Comment by dansmith65** [comment]
41b477059c595f3ae136c6a4eafa13f460cc2ddb also closed this issue; I forgot to reference it in the commit message
